[package]
name = "binius-compiler2"
version = "0.1.0"
edition = "2021"

[dependencies]
binius-core = { path = "../core" }
binius-field = { path = "../field" }
thiserror = "1.0"

[dev-dependencies]
rand = "0.8"
rand_chacha = "0.3"