[package]
name = "binius_verifier"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
binius_field = { path = "../field" }
binius_frontend = { path = "../frontend" }
binius_transcript = { path = "../transcript" }
thiserror.workspace = true
