---
version: "1.0"

# Default run configuration for mobilebench
# Customize this file to control how tests are executed

env:
  RUST_BACKTRACE: "1"
  RUST_LOG: "info"
  # Criterion benchmarks need a writable directory for results
  # {WRITABLE_DIR} is replaced with the app's writable directory at runtime
  CRITERION_HOME: "{WRITABLE_DIR}/criterion"

settings:
  default_timeout_seconds: 300  # 5 minutes

defaults:
  "test.*":
    runs:
      - name: "default"
        args: []

  "bench.*":
    runs:
      - name: "default"
        args: ["--bench"]

  "example.*":
    runs:
      - name: "default"
        args: []

# Add binary-specific configurations below
binaries:
  "example.sha256":
    runs:
      - name: "sha256_8KB"
        args: ["--max-len", "8192"]
      - name: "sha256_16KB"
        args: ["--max-len", "16384"]
      - name: "sha256_32KB"
        args: ["--max-len", "32768"]
    #   - name: "default"
    #     args: ["--max-len", "65536"]
