[package]
name = "binius-spartan-frontend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
binius-field = { path = "../field" }
bytemuck.workspace = true
smallvec.workspace = true

[lints]
workspace = true
