[package]
name = "binius-frontend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
cranelift-entity = { workspace = true }

[dev-dependencies]
rand = { workspace = true, features = ["std_rng", "thread_rng"] }
hex-literal = { workspace = true }
num-bigint = { workspace = true }
num-integer = { workspace = true }
proptest = { workspace = true }
