[package]
name = "binius-frontend"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]

[dev-dependencies]
hex-literal = "1.0.0"
base64 = "0.21"
hex = "0.4.3"
quickcheck = "1.0"
quickcheck_macros = "1.0"
