[package]
name = "binius_prover"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
binius_field = { path = "../field" }
binius_frontend = { path = "../frontend" }
binius_transcript = { path = "../transcript" }
binius_verifier = { path = "../verifier" }
thiserror.workspace = true

[dev-dependencies]
blake2.workspace = true
