name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

concurrency:
  group: ${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}

jobs:
  pre-commit:
    name: pre-commit-${{ matrix.expand.name }}
    runs-on: ${{ matrix.expand.runner }}
    strategy:
      fail-fast: false
      matrix:
        expand:
          - runner: "ubuntu-arm64-2core-8gb"
            name: "arm64"
          - runner: "ubuntu-24.04"
            name: "x86_64"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
        env:
          SKIP: "clippy"

  rust-checks:
    name: rust-checks-${{ matrix.expand.name }}
    runs-on: ${{ matrix.expand.runner }}
    strategy:
      fail-fast: false
      matrix:
        expand:
          - runner: "ubuntu-arm64-2core-8gb"
            name: "arm64"
          - runner: "ubuntu-24.04"
            name: "x86_64"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: clippy
      - name: Run platform diagnostics
        run: cargo test -p binius-utils --features platform-diagnostics test_platform_diagnostics -- --nocapture
      - name: Run platform diagnostics (native)
        run: RUSTFLAGS="-C target-cpu=native" cargo test -p binius-utils --features platform-diagnostics test_platform_diagnostics -- --nocapture
      - name: Run clippy
        run: cargo clippy --all --all-features --tests --benches --examples -- -D warnings
      - name: Run tests (binius-field)
        run: cargo test -p binius-field -j 4
      - name: Run tests (other crates)
        run: cargo test --workspace --exclude binius-field -j 4
      - name: Run tests (all-features)
        run: cargo test --all --all-features -j 4

  rust-doc:
    name: rust-doc
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Build documentation
        run: cargo doc --document-private-items --no-deps
